# Generated by Django 3.1 on 2020-11-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('personal_email', models.CharField(max_length=100, null=True)),
                ('official_mail', models.CharField(max_length=100, null=True)),
                ('phone_num', models.CharField(max_length=100, null=True)),
                ('aadhar_num', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('father_official_mail', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('mother_official_mail', models.CharField(max_length=100, null=True)),
                ('sibling_name', models.CharField(max_length=100, null=True)),
                ('sibling_mail', models.CharField(max_length=100, null=True)),
                ('sibling_num', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
