# Generated by Django 3.1 on 2020-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atten_manag_sys', '0003_auto_20201122_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=5)),
                ('section', models.CharField(default='', max_length=1)),
                ('year', models.IntegerField(default=1)),
                ('no_of_students', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(default='', max_length=10)),
                ('subject_name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAttendenceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_count', models.IntegerField(default=0)),
            ],
        ),
    ]
