# Generated by Django 3.1 on 2020-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atten_manag_sys', '0004_class_faculty_student_subject_subjectattendencetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='student_user',
            name='university_roll_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
